---
title: "Vistas Dinámicas"
output: 
  html_document:
    theme: journal
    highlight: zenburn
    toc: true
    toc_depht: 2
    toc_float: true
runtime: shiny    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Día 28: Diagramas de cuerdas

Los datos fueron obtenidos desde [Directorio de Transporte Público Metropolitano](http://www.dtpm.gob.cl/index.php/documentos/matrices-de-viaje) como tablas agregadas para el año 2019. Se muestra la variable "Viaje Laboral Promedio".


```{r, echo = F, warning=F, message=F}
library(tidyverse)
library(chorddiag)
library(hms)
library(shiny)


datos <- read_csv2("data/matriz_viajes.csv")
horas <- unique(datos$MediaHora)
horast <- hms(horas)
names(horas) <- horast
comunas <- unique(datos$ComunaSubida)

ui <- shinyUI(
  fluidPage(
  br(),
  br(),
  selectInput("n_hora", label = "Hora de Salida",
              choices = horas, selected = 27000),
  chorddiagOutput("distPlot", height = 400)
))


server <- shinyServer(function(input, output) {
  
  
  output$distPlot <- renderChorddiag({
    
    library(chorddiag)
    library(tidyverse)
    library(hms)
  
      
    datos <- datos %>% 
      filter(MediaHora == input$n_hora) %>%
      select(1,2,4) %>%
      mutate(ComunaSubida = factor(ComunaSubida, levels = comunas),
             ComunaBajada = factor(ComunaBajada, levels = comunas)) %>% 
      mutate_if(is.character, str_to_title) %>%
      spread(value = ViajeLaboralPromedio , key= ComunaBajada, drop = F, fill = 0) %>%
      column_to_rownames("ComunaSubida") %>%
      as.matrix()
    
    ticks <- ifelse(max(datos)>600, 500, ifelse(max(datos)<100, 5, 20))
    
    chorddiag(
      datos,
      groupnameFontsize = 8,
      ticklabelFontsize = 6,
      tickInterval = ticks,
      showZeroTooltips = F,  
      chordedgeColor = NA
    )
    
  })
  
})

shinyApp(ui, server, options = list(height = 600, width = 800))
```
